# CryptoLib uses libgcrypt from the shared native runtime base.
FROM ghcr.io/voyagertechnologies-public/shire-native-runtime:0.0.0
ENV LD_LIBRARY_PATH=/app
COPY build/libcryptolib.so /app/libcryptolib.so
COPY build/support/standalone /app/standalone
WORKDIR /app
CMD ["/app/standalone"]
